#! /bin/sh

export WAYLAND_DISPLAY="wayland-0"
export XDG_RUNTIME_DIR=/run/weston/xdg_runtime

export COG_PLATFORM_FDO_VIEW_FULLSCREEN=${COG_PLATFORM_FDO_VIEW_FULLSCREEN:-1}

export COG_PLATFORM_FDO_VIEW_WIDTH=${COG_PLATFORM_FDO_VIEW_WIDTH=:-1280}
export COG_PLATFORM_FDO_VIEW_HEIGHT=${COG_PLATFORM_FDO_VIEW_HEIGHT:-720}
export GALLIUM_HUD=${GALLIUM_HUD:-}

export PULSE_SERVER=${WPE_PULSE_SERVER:-unix:/run/pulse/pulseaudio.socket}


function launch
{
	while true
	do
        killall /usr/bin/cog
        echo "Launching Cog for $@ ..."
        /usr/bin/cog -P fdo $@
	done
}

( launch $@ )&
