FROM igalia/balena-browser-wpe:%%BALENA_MACHINE_NAME%%-b7e469c

COPY wpe-init /wpe-init
RUN chmod +x /wpe-init

COPY cog-fdo /usr/bin/
RUN chmod +x /usr/bin/cog-fdo

COPY cog-open /usr/bin/
RUN chmod +x /usr/bin/cog-open

CMD [ "/wpe-init" ]

ENV TOHORA_VERSION=0.3.2
RUN wget -O tohora.tgz \
    "https://github.com/mozz100/tohora/releases/download/v"$TOHORA_VERSION"/tohora_"$TOHORA_VERSION"_Linux_armv5.tar.gz" \
    && tar xzf tohora.tgz \
    && rm tohora.tgz

