#!/bin/sh

URL=${WPE_URL:-https://wpewebkit.org}

udevd &
udevadm trigger

# /var/tmp points to /var/volatile/tmp  what it doesn't exist
# /var/tmp is need for gstreamer to download chunks of videos
mkdir -p /var/volatile/tmp  || rm -rf /var/volatile/tmp/*

# Create XDG runtime dir
mkdir -p /run/weston/xdg_runtime
chmod 0700 /run/weston/xdg_runtime

# Launch a D-Bus daemon for cogctl
mkdir -p /run/dbus/
dbus-launch > /run/dbus/env
export $(cat /run/dbus/env)

# Start browser
cog-fdo ${URL}

# Start Tohora
./tohora 8080 "cog-open"

