#!/bin/sh

udevd -d
udevadm control --reload-rules && udevadm trigger

WESTON_IDLE_TIME=${WESTON_IDLE_TIME:-0}

export XDG_RUNTIME_DIR=/run/weston/xdg_runtime
mkdir -p /run/weston/xdg_runtime
chmod 0700 /run/weston/xdg_runtime

cat << IEOF > /weston.ini
[core]
require-input=false

[launcher]

[shell]
background-image=/data/wallpapers/wpe/wpe.jpg
background-color=0xffdddddd
background-type=scale-crop
clock-format=minutes
panel-color=0x90000000
panel-position=none
locking=false
animation=zoom
startup-animation=fade

IEOF

# Set the backlight brightness of a Raspberry touchscreen
# The environment variable RPI_BACKLIGHT can be set to a value 0-255.
export RPI_BACKLIGHT=${RPI_BACKLIGHT:-255}
if [ -f /sys/class/backlight/rpi_backlight/brightness ]; then
	echo $RPI_BACKLIGHT > /sys/class/backlight/rpi_backlight/brightness
fi

WPE_WESTON_OUTPUT_USE_CURRENT_MODE=${WPE_WESTON_OUTPUT_USE_CURRENT_MODE:-0}

# Allow usage of --current-mode, to let the host system decide the resolution
if [ "$WPE_WESTON_OUTPUT_USE_CURRENT_MODE" -eq 1 ]; then
	WESTON_CURRENT_MODE="--current-mode"
else
	WESTON_CURRENT_MODE=""
fi

weston ${WESTON_CURRENT_MODE} --idle-time ${WESTON_IDLE_TIME} --tty 2 -c /weston.ini
